### ISSUE TITLE
incorrect selector atom-text-editor::shadow

### ISSUE THREAD

**Issue by db47h** [Alchiadus/base16-syntax#13]
atom-text-editor.less uses
```css
    atom-text-editor,
    atom-text-editor::shadow {
        ...
```
instead of:
```css
    atom-text-editor, :host {
        ...
```
See https://atom.io/docs/latest/upgrading/upgrading-your-syntax-theme (::shadow should only be used by UI themes as far as I understand)

This causes a theme bleeding effect when changing the syntax theme from base-16-syntax to any other, with many styles from base-16-syntax  taking precedence over those of the newly selected theme.

**Comment by Alchiadus** [comment]
Good catch, thanks! I thought I read in another upgrade guide the `atom-text-editor::shadow` selector should be used, but I can't find a link to it anymore to see if that guide needs to be fixed as well. I'll release a fix for this right away.

**Comment by db47h** [comment]
Thanks for the fix, great theme btw! The other guide you mention is probably this one: https://atom.io/docs/v0.186.0/upgrading/upgrading-your-ui-theme. The fact that it does not mention syntax themes (or at least how UI themes interact or interfere with syntax ones) got me confused as well.
