### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by idleberg** [Alchiadus/base16-syntax#14]
I was wondering what's the point in removing all credits? I would think it wouldn't hurt to keep them as a comment in the LESS files, like in the original YML files. There's at least one Creative Commons theme in your selection and you're violation its terms.

I'm not concerned about my own themes, this is meant as general criticism.

**Comment by Alchiadus** [comment]
> I was wondering what's the point in removing all credits?

Certainly wasn't done on purpose, a (stupid) oversight when extracting the colors from the YML files. Do you think a comment in the LESS files is sufficient, or should I add the authors of each separate theme to the Credits section of the README too?

**Comment by idleberg** [comment]
I guess since it's just comments in the original YML, it will be fine to keep it that way

**Comment by Alchiadus** [comment]
Alright, thank you for bringing this to my attention. I'll add the respective authors to each scheme and release a new version.
