### ISSUE TITLE
Highlighting of python operator keywords

### ISSUE THREAD

**Issue by Evpok** [Alchiadus/base16-syntax#27]
We have the same issue as https://github.com/chriskempson/base16-vim/issues/29

![screenshot](https://user-images.githubusercontent.com/1656541/26973103-0b3ebee8-4d15-11e7-8e9c-585d0947ad0b.png)

That is : python operator keywords `in`, `not`, `and`, `is` and `or` are not highlighted. I understand that the rationale for not highlighting operator is to avoid distraction in long arithmetic expression, but those, particularly `in` that is part of the `for … in …:` construct don't look good this way.

Now base16-vim solved this issue by using the `pythonOperator` class provided by vim's Python highlighting, but this solution would probably not be practical in atom (especially given the current `language-python`/`MagicPython` conundrum we have right now). What we could do would be changing `syntax--operator` in [language.less](https://github.com/Alchiadus/base16-syntax/blob/master/styles/language.less#L81) to `syntax--arithmetic`, which would still keep arithmetic operator lowlighted but highlight those keywords.

**Comment by Alchiadus** [comment]
Thank you for digging into this and for providing a solution. Excluding only `syntax--arithmetic` from being highlighted looks indeed like the most sensible thing to do. I will make the change and push a new release soon.
