### ISSUE TITLE
Shadow DOM support

### ISSUE THREAD

**Issue by Alchiadus** [Alchiadus/base16-syntax#4]
Since Atom 's [166](https://github.com/atom/atom/releases/tag/v0.166.0) release Shadow DOM is enabled by default. Currently the theme does not support this yet.

As soon as I have some free time I plan to add full Shadow DOM support, until then please turn off the Shadow DOM in the Settings View if you wish to use the theme.

See also: http://blog.atom.io/2015/01/05/enable-shadow-dom.html

**Comment by chriskrycho** [comment]
:+1: Just came here to see if you already had an issue open for this.
