### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Alchiadus** [Alchiadus/base16-syntax#6]
From `Deprecation Cop`:
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Applications\Atom\resources\app\src\atom.js:55:11)
Base16.activate (c:\Users\Philippe\.atom\packages\base16-syntax\lib\base16.coffee:27:9)
```

**Comment by arteezy** [comment]
Any plans to fix this issue? Since you're the author, should be easy for you.

**Comment by Alchiadus** [comment]
I sure do. Lately I've been busy with other things leaving very little spare time, but next weekend I plan to update the theme to the new API calls, add Shadow Dom support and pull in the new Base16 themes from https://github.com/chriskempson/base16. Apologies for the delay!
